### ISSUE TITLE
ClassCastException spam in server console

### ISSUE THREAD

**Issue by Symphonic3** [APDevTeam/Movecraft-Warfare#25]
Hello! I got a recent message from a server owner I'm helping out and this stack trace is appearing in the console every so often. I assume it has to do with this check in /sign/RegionDamagedSign not working properly: `if (event.getClickedBlock() == null || !event.getClickedBlock().getType().name().contains("WALL_SIGN"))`

Here is the stacktrace:

`java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.block.CraftChest cannot be cast to class org.bukkit.block.Sign (org.bukkit.craftbukkit.v1_17_R1.block.CraftChest and org.bukkit.block.Sign are in unnamed module of loader 'app')
        at net.countercraft.movecraft.warfare.sign.RegionDamagedSign.onSignRightClick(RegionDamagedSign.java:31) ~[Movecraft-Warfare (11).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1023.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-228]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-228]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-228]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-228]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:538) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:510) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1735) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1363) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1342) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1335) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1473) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1203) ~[patched_1.17.1.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Paper-228]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by TylerS1066** [comment]
EDIT 2: Please try this dev build and report back: [removed]

EDIT: Err, the build failed because of Combat's CI failing because of it using the Movecraft Tag API which isn't in an alpha release yet.  ~~Gimme a few minutes to upload a build myself.~~

~~Please try this dev build and report back: https://github.com/APDevTeam/Movecraft-Warfare/actions/runs/1390132152~~

I think it should fix the issue.  The problem was the material name check was the old method used in <1.12, but for 1.13+ Movecraft switched to an instanceof Sign check, and Warfare wasn't updated.

**Comment by TylerS1066** [comment]
Did the dev build fix your problem?

If I don't hear back soon, I'm going to assume it did and close this issue.

**Comment by Symphonic3** [comment]
no, according to the server owner the plugin still isn't working properly
for him but i'm unsure if it's the same issue or not.

**Comment by TylerS1066** [comment]
Please do double check with the server owner since I believe that issue to have been solved.
